# Generated by Django 5.2.3 on 2025-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0004_batterytest_testresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testresult',
            name='phase',
            field=models.CharField(choices=[('pre', 'Pre season'), ('mid', 'Mid season'), ('before', 'Before Tournament')], default='pre', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('boxer', 'test', 'phase')},
        ),
    ]
