# Generated by Django 5.2.3 on 2025-08-12 20:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0005_alter_testresult_unique_together_testresult_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('pre', 'Pre season'), ('mid', 'Mid season'), ('before', 'Before Tournament')], max_length=10)),
                ('bpm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(240)])),
                ('measured_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boxer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rates', to='BoxersPresenceApp.boxer')),
            ],
            options={
                'ordering': ['-measured_at', '-updated_at'],
                'unique_together': {('boxer', 'phase')},
            },
        ),
    ]
