# Generated by Django 5.2.3 on 2025-08-12 21:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0006_heartrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('pre', 'Pre season'), ('mid', 'Mid season'), ('before', 'Before Tournament')], max_length=10)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('measured_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boxer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='BoxersPresenceApp.boxer')),
            ],
            options={
                'ordering': ['-measured_at', '-updated_at'],
                'unique_together': {('boxer', 'phase')},
            },
        ),
    ]
