# Generated by Django 5.2.3 on 2025-08-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0007_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
