# Generated by Django 5.2.3 on 2025-08-27 15:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0009_parentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('timezone', models.CharField(default='Europe/Brussels', max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='boxer',
            name='coach',
        ),
        migrations.AddField(
            model_name='boxer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boxer',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='ClassTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('rrule', models.TextField()),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('coaches', models.ManyToManyField(blank=True, related_name='class_templates', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_templates', to='BoxersPresenceApp.gym')),
            ],
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coach_profiles', to='BoxersPresenceApp.gym')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='BoxersPresenceApp.classtemplate')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='BoxersPresenceApp.gym')),
            ],
        ),
        migrations.AddField(
            model_name='boxer',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxers', to='BoxersPresenceApp.gym'),
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], max_length=12)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('boxer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendance', to='BoxersPresenceApp.boxer')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='BoxersPresenceApp.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_from', models.DateField(default=django.utils.timezone.now)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('boxer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='BoxersPresenceApp.boxer')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='BoxersPresenceApp.classtemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['template', 'active_from', 'active_until'], name='BoxersPrese_templat_085f4a_idx')],
                'unique_together': {('template', 'boxer', 'active_from')},
            },
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['gym', 'starts_at'], name='BoxersPrese_gym_id_aecdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['template', 'starts_at'], name='BoxersPrese_templat_33254f_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['session'], name='BoxersPrese_session_72def9_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionattendance',
            index=models.Index(fields=['boxer'], name='BoxersPrese_boxer_i_eb49f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'boxer')},
        ),
    ]
