# Generated by Django 5.2.3 on 2025-08-27 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0012_alter_boxer_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxer',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxers', to='BoxersPresenceApp.gym'),
        ),
    ]
