# Generated by Django 5.2.5 on 2025-08-29 10:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0013_alter_boxer_gym'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='batterytest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='classsession',
            options={'ordering': ['-start']},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-measured_at']},
        ),
        migrations.RemoveIndex(
            model_name='classsession',
            name='BoxersPrese_gym_id_aecdd6_idx',
        ),
        migrations.RemoveIndex(
            model_name='classsession',
            name='BoxersPrese_templat_33254f_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='BoxersPrese_templat_085f4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='sessionattendance',
            name='BoxersPrese_session_72def9_idx',
        ),
        migrations.RemoveIndex(
            model_name='sessionattendance',
            name='BoxersPrese_boxer_i_eb49f2_idx',
        ),
        migrations.RenameField(
            model_name='classsession',
            old_name='ends_at',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='classsession',
            old_name='starts_at',
            new_name='start',
        ),
        migrations.AlterUniqueTogether(
            name='batterytest',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='heartrate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('boxer', 'date')},
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='version',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('boxer', 'template')},
        ),
        migrations.RemoveField(
            model_name='gym',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='marked_at',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='marked_by',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sessionattendance',
            name='weight',
        ),
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together={('boxer', 'phase', 'measured_at')},
        ),
        migrations.AddField(
            model_name='boxer',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='boxers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boxer',
            name='shared_with_gyms',
            field=models.ManyToManyField(blank=True, help_text='Gyms that can view this boxer and their data.', related_name='shared_boxers', to='BoxersPresenceApp.gym'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='classsession',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='excused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testresult',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testresult',
            name='measured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='testresult',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='boxer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='BoxersPresenceApp.boxer'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='batterytest',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battery_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batterytest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batterytest',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batterytest',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='batterytest',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boxer',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxers', to='BoxersPresenceApp.gym'),
        ),
        migrations.AlterField(
            model_name='boxer',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='boxer',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='BoxersPresenceApp.gym'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='BoxersPresenceApp.classtemplate'),
        ),
        migrations.AlterField(
            model_name='classtemplate',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_templates', to='BoxersPresenceApp.gym'),
        ),
        migrations.AlterField(
            model_name='classtemplate',
            name='rrule',
            field=models.TextField(help_text='RFC5545 RRULE string'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coaches', to='BoxersPresenceApp.gym'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='bpm',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='measured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='phase',
            field=models.CharField(choices=[('prep', 'Preparation'), ('build', 'Build'), ('peak', 'Peak')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sessionattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='BoxersPresenceApp.classsession'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='phase',
            field=models.CharField(choices=[('prep', 'Preparation'), ('build', 'Build'), ('peak', 'Peak')], max_length=10),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='value1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='value2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='value3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='measured_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weight',
            name='phase',
            field=models.CharField(choices=[('prep', 'Preparation'), ('build', 'Build'), ('peak', 'Peak')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='heartrate',
            unique_together={('boxer', 'phase', 'measured_at')},
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('boxer', 'test', 'phase', 'measured_at')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='active_from',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='active_until',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='expected_kg',
        ),
    ]
