# Generated by Django 5.2.5 on 2025-08-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0014_alter_attendance_options_alter_batterytest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
