# Generated by Django 5.2.5 on 2025-08-29 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0015_gym_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coaches', to='BoxersPresenceApp.gym'),
        ),
    ]
