# Generated by Django 5.2.5 on 2025-08-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0016_alter_coachprofile_gym'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ['-measured_at']},
        ),
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='weight',
            name='kg',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.RemoveField(
            model_name='weight',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='updated_at',
        ),
    ]
