# Generated by Django 5.2.5 on 2025-08-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0017_alter_weight_options_alter_weight_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='value',
        ),
    ]
