# Generated by Django 5.2.5 on 2025-08-30 16:23

from django.db import migrations, models


def forwards(apps, schema_editor):
    TR = apps.get_model("BoxersPresenceApp", "TestResult")
    alias = {
        "pre": "prep", "Pre": "prep", "PRE": "prep", "Preparation": "prep",
        "mid": "build", "Mid": "build", "MID": "build", "build": "build", "Build": "build",
        "before": "peak", "Before": "peak", "before tournament": "peak",
        "Before Tournament": "peak", "peak": "peak", "PEAK": "peak",
    }
    for old, new in alias.items():
        TR.objects.filter(phase=old).update(phase=new)

def backwards(apps, schema_editor):
    TR = apps.get_model("BoxersPresenceApp", "TestResult")
    # If you really need a reverse, map canonical back to your original labels:
    TR.objects.filter(phase="prep").update(phase="Pre")
    TR.objects.filter(phase="build").update(phase="Mid")
    # peak stays peak

class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0018_remove_testresult_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='phase',
            field=models.CharField(choices=[('prep', 'Preparation'), ('build', 'Build'), ('peak', 'Peak')], db_index=True, max_length=16),
        ),
    ]
