# Generated by Django 5.2.5 on 2025-08-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0019_alter_testresult_phase'),
        ('BoxersPresenceApp', '0020_normalize_testresult_phase'),
    ]

    operations = [
    ]
