# Generated by Django 5.2.5 on 2025-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0021_merge_20250830_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heartrate',
            options={'ordering': ['-measured_at']},
        ),
        migrations.AlterUniqueTogether(
            name='heartrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='heartrate',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='bpm',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='measured_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.RemoveField(
            model_name='heartrate',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='heartrate',
            name='updated_at',
        ),
    ]
