# Generated by Django 5.2.5 on 2025-09-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0022_alter_heartrate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtemplate',
            name='ends_on',
        ),
        migrations.RemoveField(
            model_name='classtemplate',
            name='location',
        ),
        migrations.RemoveField(
            model_name='classtemplate',
            name='rrule',
        ),
        migrations.RemoveField(
            model_name='classtemplate',
            name='starts_on',
        ),
        migrations.AddField(
            model_name='classtemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
