# Generated by Django 5.2.5 on 2025-09-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0023_remove_classtemplate_ends_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxer',
            name='parent_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
