# Generated by Django 5.2.5 on 2025-09-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0024_boxer_parent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxer',
            name='shared_with_gyms',
            field=models.ManyToManyField(blank=True, related_name='shared_boxers', to='BoxersPresenceApp.gym'),
        ),
    ]
