# Generated by Django 5.0.4 on 2025-09-02 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0025_alter_boxer_shared_with_gyms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classtemplate',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
