# Generated by Django 5.2.3 on 2025-09-05 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0026_alter_classtemplate_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boxer',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='Parent accounts who can view this boxer’s attendance and weight', related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boxer',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='coached_boxers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='children',
            field=models.ManyToManyField(blank=True, help_text='Boxers this parent/guardian can view', related_name='parent_profiles', to='BoxersPresenceApp.boxer'),
        ),
    ]
