# Generated by Django 5.2.3 on 2025-09-06 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0027_boxer_parents_alter_boxer_coaches_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='BoxersPresenceApp.classsession'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('boxer', 'date', 'session')},
        ),
        migrations.DeleteModel(
            name='SessionAttendance',
        ),
    ]
