# Generated by Django 5.2.6 on 2025-09-17 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0028_alter_attendance_unique_together_attendance_session_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='BoxersPresenceApp.classtemplate'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='session',
        ),
        migrations.DeleteModel(
            name='ClassSession',
        ),
    ]
