# Generated by Django 5.2.3 on 2025-09-08 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0028_alter_attendance_unique_together_attendance_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxer',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boxers', to='BoxersPresenceApp.gym'),
        ),
    ]
