# Generated by Django 5.2.6 on 2025-09-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0029_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('boxer', 'date', 'class_template')},
        ),
    ]
