# Generated by Django 5.2.6 on 2025-09-17 17:48

from django.db import migrations, models

def split_name(apps, schema_editor):
    Boxer = apps.get_model("BoxersPresenceApp", "Boxer")
    for boxer in Boxer.objects.all():
        nm = (getattr(boxer, "name", "") or "").strip()
        if not nm:
            continue
        parts = nm.split(" ", 1)
        boxer.first_name = parts[0]
        if len(parts) > 1:
            boxer.last_name = parts[1]
        boxer.save(update_fields=["first_name", "last_name"])

class Migration(migrations.Migration):

    dependencies = [
        ("BoxersPresenceApp", "0031_backfill_class_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="boxer",
            name="first_name",
            field=models.CharField(max_length=120, blank=True),
        ),
        migrations.AddField(
            model_name="boxer",
            name="last_name",
            field=models.CharField(max_length=120, blank=True),
        ),
        migrations.RunPython(split_name, reverse_code=migrations.RunPython.noop),
    ]
