# Generated by Django 5.2.6 on 2025-09-27 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0032_auto_20250917_1948'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('boxer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='BoxersPresenceApp.boxer')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxer_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
