# Generated by Django 5.2.6 on 2025-11-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxersPresenceApp', '0033_boxercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified')], db_index=True, default='U', max_length=1),
        ),
    ]
